DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  AUTHOR VARCHAR(100) NOT NULL,
  BOOK_TYPE INT NOT NULL,
  PRICE FLOAT NOT NULL,
  ISBN INT UNIQUE NOT NULL
);

DROP TABLE IF EXISTS BOOK_TYPE;

CREATE TABLE BOOK_TYPE (
  ID INT PRIMARY KEY,
  TYPE_DESC VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS DISCOUNT;

CREATE TABLE DISCOUNT (
  ID INT PRIMARY KEY,
  BOOK_TYPE INT,
  PROMOCODE VARCHAR(10),
  DISCOUNT FLOAT NOT NULL,
  DISCOUNT_TYPE INT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  IS_ACTIVE SMALLINT NOT NULL
);